/*
===========================================================================
Copyright (C) 2026 Tremulous bot support contributors

This file is part of Tremulous.

Tremulous is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License,
or (at your option) any later version.

Tremulous is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Tremulous; if not, see <https://www.gnu.org/licenses/>

===========================================================================
*/

// g_bot.h -- server-side bots: shared definitions
//
// The bot system is split in four files:
//   g_bot.c       bot management, console commands, cvars, per-frame driver
//   g_botnav.c    navigation graph built from the map's collision model,
//                 A* path finding and path following
//   g_botai.c     decision making: perception, aiming, combat, alien
//                 abilities and goals
//   g_botbuild.c  team knowledge, human shopping, alien evolution and
//                 base building
//
// Everything is plain C89 so it also compiles to a QVM.

#ifndef G_BOT_H
#define G_BOT_H

/*
===========================================================================

NAVIGATION

The navigation graph is generated by flood-filling the map's collision
model with hull traces (the same traces player movement uses), starting
from every spawn point, buildable and teleporter destination. Nodes sit
on walkable floor on a regular grid; edges record how the step between
two nodes is made (walk, jump, drop, wall climb, ladder, teleport) and
which hull sizes fit through. Wall walking aliens get "climb" edges up
any vertical surface, so they use walls to reach ledges other classes
cannot.

===========================================================================
*/

#define NAV_MAX_NODES       32768
#define NAV_MAX_EDGES       ( NAV_MAX_NODES * 8 )
#define NAV_MAX_EXTRA       256       // teleporter edges, added after generation
#define NAV_HASH_SIZE       16384     // power of two
#define NAV_MAX_PATH        384

#define NAV_STEPSIZE        18.0f
#define NAV_MAX_DROP        1024.0f
#define NAV_MAX_CLIMB       512.0f

// hull classes: every player class maps to one of these
typedef enum
{
  NAV_HULL_SMALL,   // dretch
  NAV_HULL_MEDIUM,  // basilisks, grangers, marauders
  NAV_HULL_HUMAN,   // human
  NAV_HULL_DRAGOON, // dragoons
  NAV_HULL_LARGE,   // tyrant
  NAV_HULL_TALL,    // battlesuit: human width, extra height

  NAV_NUM_HULLS
} navHull_t;

// node flags
#define NAVN_HAZARD     0x01  // lava, slime, trigger_hurt, bottomless pit
#define NAVN_WATER      0x02
#define NAVN_EXTRA      0x04  // has entries in the extra (teleporter) edge list
#define NAVN_SEED       0x08  // created from a seed entity
#define NAVN_EDGE       0x10  // next to a fall into the void or a kill zone

// edge flags
#define NAVE_DROP       0x01  // walk off a ledge (dz < -STEPSIZE)
#define NAVE_CLIMB      0x02  // needs vertical ability: jump / wall climb / jetpack
#define NAVE_LADDER     0x04  // the climbed surface is a ladder
#define NAVE_TELEPORT   0x08
#define NAVE_DOOR       0x10  // passes through a (temporarily unlinked) door

typedef struct
{
  float           origin[ 3 ];  // point on the floor
  int             firstEdge;
  short           numEdges;       // (signed: q3asm can't store unsigned shorts)
  unsigned char   flags;
  unsigned char   hulls;        // bit per navHull_t that fits standing here
  short           cx, cy;       // grid cell
  int             hashNext;
} navNode_t;

typedef struct
{
  short           target;       // node number (NAV_MAX_NODES fits a signed short)
  unsigned char   flags;
  unsigned char   hulls;        // bit per navHull_t that can traverse
  short           dz;           // target.z - source.z
  short           climb;        // vertical clearance needed above source floor
  short           cost;         // travel cost (roughly distance in units)
  short           pad;
} navEdge_t;

typedef struct
{
  int             from;
  navEdge_t       edge;
} navExtraEdge_t;

// what a particular bot can traverse (filled from its class)
typedef struct
{
  navHull_t       hull;
  float           maxClimb;     // tallest climb without help
  float           maxDrop;      // longest drop considered safe
  qboolean        wallClimber;  // can climb any wall
  qboolean        ladders;
  qboolean        jetpack;
  team_t          team;         // for danger avoidance
} navCaps_t;

typedef enum
{
  NAVSTATE_NONE,       // no graph
  NAVSTATE_BUILDING,   // generation in progress
  NAVSTATE_READY
} navState_t;

extern navNode_t       navNodes[ NAV_MAX_NODES ];
extern navEdge_t       navEdges[ NAV_MAX_EDGES ];
extern int             navNumNodes;
extern int             navNumEdges;
extern navState_t      navState;

void      BotNav_Init( void );
void      BotNav_Shutdown( void );
void      BotNav_Frame( void );
void      BotNav_StartGeneration( qboolean force );
qboolean  BotNav_Ready( void );
void      BotNav_PrintInfo( void );
qboolean  BotNav_Save( void );

void      BotNav_CapsForClass( class_t pclass, team_t team, qboolean jetpack, navCaps_t *caps );
int       BotNav_NearestNode( const vec3_t pos, const navCaps_t *caps, qboolean needVisible );
int       BotNav_FindPath( int start, int goal, const navCaps_t *caps,
                           int *pathEdges, int maxLen, int *pathLen );
int       BotNav_FindPathToNearest( int start, const navCaps_t *caps,
                                    qboolean ( *isGoal )( int node, void *data ), void *data,
                                    int maxDist, int *pathEdges, int maxLen, int *pathLen );
qboolean  BotNav_EdgeUsable( const navEdge_t *e, const navCaps_t *caps );
navEdge_t *BotNav_Edge( int edgeNum );
int       BotNav_EdgeSource( int edgeNum );
void      BotNav_Flood( int start, const navCaps_t *caps, float maxDist, float *distOut );
void      BotNav_ShowFor( gentity_t *viewer, float radius, int seconds );
void      BotNav_ClearShow( void );
void      BotNav_HullBounds( navHull_t hull, vec3_t mins, vec3_t maxs );
int       BotNav_RandomNodeNear( const vec3_t pos, float minDist, float maxDist, const navCaps_t *caps );
int       BotNav_RandomReachable( int start, const navCaps_t *caps, float minDist, float maxDist,
                                  const vec3_t near, float nearRadius );

/*
===========================================================================

BOT STATE

===========================================================================
*/

#define BOT_MAX_SKILL     10

typedef enum
{
  BROLE_ATTACK,     // push to the enemy base
  BROLE_DEFEND,     // hang around our own base
  BROLE_BUILDER,    // granger / construction kit
  BROLE_ROAM        // hunt enemy players wherever they are
} botRole_t;

typedef enum
{
  BGOAL_NONE,
  BGOAL_FIGHT,       // shooting / clawing an enemy we can see
  BGOAL_HUNT,        // moving toward an enemy we know about
  BGOAL_ATTACKBASE,  // moving toward an enemy structure
  BGOAL_DEFEND,      // patrolling our base
  BGOAL_ARMOURY,     // human: walking to an armoury to shop
  BGOAL_HEAL,        // walking to a medistation / booster / creep
  BGOAL_BUILD,       // walking to a build spot
  BGOAL_REPAIR,      // human builder repairing a structure
  BGOAL_EVOLVE,      // alien: find a safe spot to evolve
  BGOAL_FLEE,        // getting away from danger
  BGOAL_ROAM,        // wander to a random spot

  BGOAL_NUM
} botGoal_t;

typedef enum
{
  BMOVE_NONE,
  BMOVE_PATH,
  BMOVE_DIRECT
} botMoveMode_t;

// personality: drawn at random when the bot is added, steers the
// decision trees so a team of bots doesn't all do the same thing
typedef struct
{
  float           aggression;   // 0..1: rush vs hang back
  float           saver;        // 0..1: alien saves evos for big classes / human saves credits
  int             weaponPref;   // index into the human weapon preference tables
  int             alienPref;    // preferred line of evolution
} botPersonality_t;

typedef struct bot_s
{
  qboolean        inuse;
  int             clientNum;
  int             skill;
  team_t          wantTeam;     // TEAM_NONE == pick automatically
  botPersonality_t pers;

  // timing
  int             spawnedAt;
  int             nextDecision;
  int             nextTeamTry;
  int             nextClassTry;
  int             nextChat;

  // role and goal
  botRole_t       role;
  int             nextRoleCheck;
  int             goalFailCount;      // roam/defend goals in a row we couldn't path to
  int             lastGoalFail;
  botGoal_t       goal;
  int             goalEnt;          // entity number or -1
  vec3_t          goalPos;
  int             goalNode;
  int             goalSetTime;
  int             goalTimeout;
  int             forcedGoalUntil;  // botgoto
  vec3_t          forcedGoal;
  qboolean        forcedReached;

  // perception
  int             enemy;            // entity number or -1
  int             enemySeenTime;    // last time we had line of sight
  int             enemyFirstSeen;   // for reaction time
  vec3_t          enemyLastPos;
  vec3_t          enemyLastVel;
  int             lastAttacker;
  int             lastHurtTime;
  int             lastHealth;
  int             nextEnemyScan;

  // combat movement
  int             strafeDir;
  int             nextStrafeChange;

  // aim
  vec3_t          viewAngles;       // what we are looking at right now
  vec3_t          aimError;         // current aim offset (degrees)
  int             nextAimErrorTime;
  float           aimFactor;        // this bot's own spread around its skill (0.85 - 1.15)
  // where the current enemy was recently, for aim delay
#define BOT_AIM_HISTORY 32
  vec3_t          aimHist[ BOT_AIM_HISTORY ];
  int             aimHistTime[ BOT_AIM_HISTORY ];
  int             aimHistHead, aimHistCount, aimHistEnt;
  // emotes
  int             emoteAt;          // press the gesture button at this time
  int             nextEmote;
  int             lastScore;
  qboolean        aimLocked;        // crosshair is on target

  // navigation
  navCaps_t       caps;
  int             path[ NAV_MAX_PATH ];   // edge numbers
  int             pathLen;
  int             pathPos;
  int             pathGoalNode;
  int             pathStart;            // node the path starts from
  int             pathTime;
  int             pathFailTime;
  int             curNode;
  int             nextSmooth;
  int             badEdge;              // edge we got stuck on
  int             badEdgeUntil;
  botMoveMode_t   moveMode;

  // stuck detection
  vec3_t          stuckPos;
  int             stuckCheckTime;
  int             stuckCount;
  int             unstickUntil;
  float           unstickYaw;
  int             lastJumpTime;

  // the command being assembled this frame
  usercmd_t       cmd;
  float           moveYaw;          // yaw we want to move along
  qboolean        wantMove;
  qboolean        walk;
  int             upmove;
  int             buttons;
  int             lastButtons;
  qboolean        wantWallclimb;
  qboolean        forceView;        // movement needs to control the view this frame

  // abilities
  int             chargeStart;      // pounce / trample / lcannon charge start
  int             chargeFor;        // msec to hold the charge
  int             abilityCooldown;
  int             jetpackUntil;

  // human shopping
  int             lastBuyTime;
  int             creditsAtLastBuy;
  int             nextItemUse;

  // alien evolution
  int             nextEvolveTry;
  int             evolveFailures;

  // building
  int             buildType;          // buildable_t we are trying to build
  vec3_t          buildSpot;
  int             buildTries;
  int             nextBuildPlan;
  int             buildSettle;        // time we arrived at the spot
  int             buildPhase;         // 0 walking, 1 aiming, 2 placing
  float           buildYaw;
  int             buildPhaseTime;
  int             buildSpotIndex;     // defense spot being filled, or -1
  vec3_t          buildOrigin;        // where the structure will actually land
  int             repairEnt;
  int             nextBlasterSwap;

  // debugging
  qboolean        debug;
  int             nextDebugPrint;
  char            lastAction[ 64 ];
} bot_t;

extern bot_t    g_bots[ MAX_CLIENTS ];

// cvars
extern vmCvar_t bot_skill;
extern vmCvar_t bot_debug;
extern vmCvar_t bot_build;
extern vmCvar_t bot_buildersPerTeam;
extern vmCvar_t bot_chat;
extern vmCvar_t bot_fillAliens;
extern vmCvar_t bot_fillHumans;
extern vmCvar_t bot_pause;
extern vmCvar_t bot_peaceful;
extern vmCvar_t bot_navGridSize;
extern vmCvar_t bot_navAutoGenerate;
extern vmCvar_t bot_navGenBudget;
extern vmCvar_t bot_namePrefix;
extern vmCvar_t bot_aimSkillScale;
extern vmCvar_t bot_aimConeMax;
extern vmCvar_t bot_aimConeMin;
extern vmCvar_t bot_aimDelayMax;
extern vmCvar_t bot_aimDelayMin;
extern vmCvar_t bot_emote;
float     G_BotAimCone( const bot_t *bot );
int       G_BotAimDelay( const bot_t *bot );
int       G_BotPickSkill( const char *s, int fallback );
void      G_BotEmote( bot_t *bot, float chance, int delay );
extern vmCvar_t bot_evolve;
extern vmCvar_t bot_buy;

// g_bot.c
qboolean  G_BotSupported( void );
bot_t     *G_BotForClient( int clientNum );
void      G_BotCommand( bot_t *bot, const char *fmt, ... ) __attribute__ ((format (printf, 2, 3)));
void      G_BotSay( bot_t *bot, qboolean team, const char *text );
void      G_BotDebug( bot_t *bot, const char *fmt, ... ) __attribute__ ((format (printf, 2, 3)));
float     G_BotRandom( void );     // 0..1
float     G_BotCrandom( void );    // -1..1
int       G_BotRandInt( int n );   // 0..n-1

// g_botai.c
void      BotAI_Begin( bot_t *bot );
void      BotAI_Think( bot_t *bot );
void      BotAI_Spawned( bot_t *bot );
void      BotAI_TeamFrame( void );
void      BotAI_ResetPlans( void );
void      BotAI_PrintState( bot_t *bot );
qboolean  BotAI_PathToEntity( bot_t *bot, gentity_t *target );
void      BotAI_ForceGoal( bot_t *bot, const vec3_t pos );

// g_botbuild.c: team knowledge, shopping, evolving and base building
void      BotTeam_Frame( void );
gentity_t *BotTeam_HQ( team_t team );
int       BotTeam_CountBuildable( team_t team, buildable_t b, qboolean spawnedOnly );
gentity_t *BotTeam_NearestBuildable( team_t team, buildable_t b, const vec3_t pos, float maxDist );
int       BotTeam_Buildables( team_t team, int **list );
int       BotTeam_Builders( team_t team, int exclude );
qboolean  BotTeam_HaveBaseInfo( team_t team, vec3_t basePos );
qboolean  BotBuild_WantBuilderRole( bot_t *bot );
qboolean  BotBuild_Think( bot_t *bot );
void      BotBuild_ResetPlans( void );
void      BotBuild_PrintPlans( void );
qboolean  BotShop_WantsToShop( bot_t *bot );
void      BotShop_Shop( bot_t *bot );
qboolean  BotEvolve_Think( bot_t *bot, qboolean safe );
const char *BotShop_SpawnItem( bot_t *bot );

// movement helpers shared between the AI and navigation (g_botnav.c)
void      BotMove_Reset( bot_t *bot );
qboolean  BotMove_FollowPath( bot_t *bot );
qboolean  BotMove_SetGoal( bot_t *bot, const vec3_t pos, int goalNode );
void      BotMove_ClearPath( bot_t *bot );
void      BotMove_CheckStuck( bot_t *bot );
void      BotMove_MoveToward( bot_t *bot, const vec3_t pos );
qboolean  BotMove_SafeDirection( bot_t *bot, float yaw );
qboolean  BotMove_FindSafeYaw( bot_t *bot, float *yaw );
void      BotMove_MoveTowardSafe( bot_t *bot, const vec3_t pos );
qboolean  BotMove_Unstick( bot_t *bot );
void      BotMove_EdgeGuard( bot_t *bot );
void      BotMove_UpdateCaps( bot_t *bot );

#endif
